export const MAIL_CONTENT_READ_REQUEST = "MAIL_CONTENT_READ_REQUEST";
export const MAIL_CONTENT_READ_SUCCESS = "MAIL_CONTENT_READ_SUCCESS";
export const MAIL_CONTENT_READ_FAIL = "MAIL_CONTENT_READ_FAIL";

export const MAIL_CONTENT_UPDATE_REQUEST = "MAIL_CONTENT_UPDATE_REQUEST";
export const MAIL_CONTENT_UPDATE_SUCCESS = "MAIL_CONTENT_UPDATE_SUCCESS";
export const MAIL_CONTENT_UPDATE_FAIL = "MAIL_CONTENT_UPDATE_FAIL";
export const MAIL_CONTENT_UPDATE_RESET = "MAIL_CONTENT_UPDATE_RESET";
