export const REPORT_GENERATE_REQUEST = "REPORT_GENERATE_REQUEST";
export const REPORT_GENERATE_SUCCESS = "REPORT_GENERATE_SUCCESS";
export const REPORT_GENERATE_FAIL = "REPORT_GENERATE_FAIL";

export const REPORT_DATA_REQUEST = "REPORT_DATA_REQUEST";
export const REPORT_DATA_SUCCESS = "REPORT_DATA_SUCCESS";
export const REPORT_DATA_FAIL = "REPORT_DATA_FAIL";
export const REPORT_DATA_RESET = "REPORT_DATA_RESET";
